name: todopractise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  fpdart: ^1.1.1
  dio: ^5.8.0+1
  bloc: ^9.0.0
  get_it: ^8.0.3
  path_provider: ^2.1.5
  path: ^1.9.0
  connectivity_plus: ^6.1.3
  sqflite: ^2.4.1
  flutter_screenutil: ^5.9.3
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
